//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_Project_Alamgir
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabReport
    {
        public int LabReportID { get; set; }
        public string PatientName { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string VisitingDate { get; set; }
        public string ExamName { get; set; }
        public string Price { get; set; }
    }
}
